def dry():
    koko = ['By more proactively planning product transitions and better managing clearance pricing across sales channels, we materially improved our at-risk inventory position in Q1 versus the prior year, allowing us to reinvest those dollars into the new inventories our customers want.',
    'In Canada, we are seeing positive early results from the new store redesigns we have developed in partnership with key vendors.',
    'So these are exciting categories.',
    'You noted that we have anniversaried the disruption from future shops, restructuring.',
    'In Canada specifically, we’ve mentioned in the prepared remarks that the new prototype stores that we’ve developed in partnership with the vendors are performing very promising and so there will be more on that.',
    'Number two, increased by the increased visibility of open-box and clearance inventory and number three by the expansion of online-only flash sales.',
    'These increases were primarily due to the calendar shift this year, which results in Q3 ending a week closer to the holiday season.',
    'One of the statistics that you put in your prepared comments was that more of your product is being picked up in-store, and I know that’s been a big initiative for you guys and a lot of retailers.',
    'So, as you leverage the store and as customers come to pick up their products, I just wondered if you could walk us through how that contributes to the overall profitability and how we can expect that contributing going forward.',
    'And if I can ask one other unrelated question just about GreatCall.',
    'It’s completely in line with our strategy of addressing key human needs.',
    'I would just add one more financial clarifier, so that it doesn’t send unintended messages.',
    'Those are more about the early part of the business.',
    'I think Corie, you suggested the same on the Q3 call.',
    "And I'm sure you’ve factored competition in, but I was curious if anything surprised you sort of from when you sort of started thinking about the zero to 3 to now?",
    "But one of the things I'm excited about is that the services focus is increasingly becoming a core focus of the company and that's really apparent in the way we're launching Total Tech Support.",
    "We're maybe getting a little bit of residual off of the previous agreement which could potentially not continue.",
    'And history has shown up very, very, very few to the less than 1% range of these customers go delinquent on their agreements.',
    "Okay, on the sequencing services, the strength there was driven by things like the work we're doing for gel, and so we talked about the fact that the gel projects have been over 50,000 of its 100,000 genomes and is actually on a pretty robust space in terms of working through the samples that they're getting.",
    'Publications continue to grow about 40% per year and are addressing key questions in developmental biology, immunology, neurology, and cancer.',
    'Yes, so where we are with PacBio to close on that question is, we are currently working in Phase II, as you know, with the CMA and the way that works is that they have appointed a panel that we are working with to provide the information they need to make the decision to answer questions that they have and the CMA has up to the middle of December to come back with a decision.',
    'In the second quarter alone, we saw all of us begin enrollments in the United States, a large UK Biobank study awarded and announcements from Genome Canada and the Australian government among others.',
    'More importantly, we are substantially enhancing our capabilities through four acquisitions, new strategic partnerships and significant renewals of longstanding relationships with several key renewals and new deals to be executed in the fourth quarter.',
    "Disbursements, we've talked a lot about that Disbursements of all kinds – healthcare, the gig economy, and so on.",
    'This quarter, we are beginning to have more success with FinTechs both in terms of signings but also agreements still to be contracted.',
    'Now as I previously discussed on earlier calls, we formed a new digital business team to jointly develop digital transformations with our clients, leveraging assets from across the company and our partnerships, and we are scaling this model to more than 50 accounts over the next few months.',
    'We did the same thing by the way from a payable standpoint.',
    'But to answer to your question, yes, those investments are factored in the projections that we gave you on margin expansion and on EPS.',
    'And almost 16,000 employees have completed the training and passed the certification exam, also established certification training programs with strategic partners, including AWS and Microsoft Azure.',
    'We co-created Open Health Connect with a large academic and research hospital system in New York and have also worked with several of our strategic partners including Microsoft and ServiceNow.',
    'And we have an opportunity to grow that business kind of with the economy, particularly as we see our term lending program begin to mature a bit as we shift our focus on a different kind of real estate customer.',
    'The majority of the cost savings and Agility efforts are in North America.',
    'Q1 is the lightest profit quarter.',
    "One is we have sales forces that sells to smaller companies, mid-size companies and larger companies and there's different kind of expectations.",
    'As you know, the development of our health care services within our stores is a priority for us, and we are continuing to make good progress, identifying strategic partnership that offer a balance and high-quality range of services to our store.',
    "Just wanted to go back to the aggressive shift we've seen to preferred and narrow networks over the last few years.",
    'We believe the BET legislation provides a fair balance between Dominion Energy’s customers and its shareholders and allocates the cost of this program equitably among large and small users of electricity.',
    'Financial measures will include revenue growth, operating income margin, as well as our progress on restructuring charges.',
    'In conjunction with the impairment test, the company utilized its best estimate of future revenue growth and operating margin rates as of April 30, 2017.',
    'Now, we will make up for that in other areas and one of the areas that we talked about that is very exciting for us, which we are starting to see some acceleration in the materials well you’re getting the growth from that, that does not come with the same growth, gross profit margin for us.',
    'But when you go in to ’19, the tax rate should not be a headwind or a tailwind and it’s all around underlying performance of the business that Mark already talked about.',
    'But we see rates -- if they stand where they are now, it’s neither a headwind or a tailwind for the second half of the year on a year-over-year basis.',
    'These initiatives will include pulling back on inventory receipts, cutting lead times, strengthening our assortment and store closures.',
    'For the full year, we still expect to reduce our off-price penetration within our broader wholesale channel as we strategically reposition off-price back towards its original purpose as an excess inventory clearance vehicle.',
    "And the more of those that we open, the more confident we're getting that those are long-term pluses for us, both to get us into trade areas where we can't make the economics of a larger store work but also just, in the long term, looking at larger stores that we have that have been more impacted by digital sales and are doing a little less volume than they used to do, there's the opportunity for us to scale down the size of the store, because we do think that that's, long term, a big positive for us.",
    'The blueprint for that effort will be a plan to reimagine all of our decision-making processes and better utilize our previous investment in technology to do so.',
    'We expect this inventory to sell off, and that would give us further capacity.',
    'During the first quarter, we were awarded a proposal update.',
    'But the timing of when we actually put something in backlog is determined by when we sign the contract, which can be months and quarters, sometimes between when we win a project and when we actually book it.',
    'While these mines are idled, we expect to meet our Brazilian customers fertilizer needs with a combination of existing rock and production inventory in Brazil, rock from our mine in Peru and MAP from Florida.',
    'We expect to liquidate this inventory as we meet our North American and Brazilian customer needs, which should allow us to maintain high operating rates and low conversion costs.',
    'Our key forward looking credit metrics continue to improve as criticized loans were at the lowest level in nearly 20 years and non-performing assets are at the lowest level since before the crisis.',
    'We have got new actors coming in who weren’t there a few quarters ago both outside the market companies who are looking to enter into the market and we have got new company formation going on, Joel mentioned the fund raising that is going on in venture.',
    "Well, remember six were awarded from the Toys', so we actually have no capital outlay there.",
    'So the A malls are getting to a point where their occupancy costs are so high that they have now started to test the waters in terms of shifting over to open air shopping centers that are surrounding the mall to see if they can see the sales transfer and still make the business make sense.',
    'Outlet tenants have now started to migrate as well to the open air shopping center.',
    "Is that a level that Microchip can comfortably operate at if we think about the intermediate term or should we expect in what would typically be a seasonally softer period like the fiscal third quarter that the company would look to replenish some inventory whether it's in the channel on hand or both.",
    "But I guess the question is when we compare that did you all seek out what the market would put on E*TRADE today did you actually seek out when get bids or have any interaction like that and as along as on that subject as well and you've been guiding the process Rodger just trying to see what your future I know the employer -- I think your employment contract ends at the end of the year and just want to see whether you'll still be guiding the shift here to the five-year and $7 of earnings.",
    "I'm going to cover four headwinds and two tailwinds in depth.",
    'Let we move to some comments on our merger and acquisition program.',
    'Looking forward, our merger and acquisition pipeline is very full.',
    'Next let me talk about brokerage, merger and acquisition growth.',
    'Next let me talk about brokerage merger and acquisition growth.',
    'Next, let me talk about brokerage merger and acquisition growth.',
    'Next, let me move to merger and acquisition growth.',
    'Let me turn to merger and acquisition growth.',
    '2018 was an outstanding merger and acquisition year.',
    'Next, let me talk about brokerage, merger and acquisition growth.',
    'Second, let me talk about brokerage merger and acquisition growth.',
    'Next let me move to merger and acquisition growth.',
    'Next, let me move to merger and acquisition growth.',
    'Second, let me talk about brokerage merger and acquisition growth.',
    'Second, let me talk about merger and acquisition growth.',
    'Next, let me move to merger and acquisition growth.',
    'There have been no changes in any of the regulatory issues, no changes with any of our contracts.',
    'This multifaceted approach to primary care enhances our ability to bring differentiated integrated care to more seniors more quick and gives us the flexibility to tailor our approach based on the differing needs of each local market.',
    'Conviva manages the clinical operations in 110 staff model centers and also provides MSO services to more than 800 independent physicians in South Florida and Texas.',
    'The first high level question is when you guys talk about headwinds, it seems to be plural, but the only one that I think I’m very comfortable with is the return of the HIF, so wondering if you could maybe walk through headwinds and tailwinds at this stage, what else we should be thinking about especially on the headwind side.',
    'The process transformation office that Bruce referenced in his partnership with our various businesses is working diligently across segments to achieve increased productivity while improving and simplifying our core processes.',
    "On the specialty side, on the specialty – sorry, the pharmacy side, the mail-order side, what we're referring to there is our mail-order rate and, as I mentioned in our low price Walmart plan, which has been and continues to be a very successful plan and a very good partnership with Walmart, we are seeing a slightly lower mail-order rate than we had anticipated.",
    'I was wondering if you could elaborate a little bit more on the new business wins, specifically at success at expanding the pool of awards with some of the smaller trial activity?',
    'Other services there on our Faster Payments strategy, we have now launched AML Insights, which is our network-level anti-money laundering solution, currently in the UK.',
    "So if you think about the headcount, again relatively flat on a Q4 versus Q4 basis, but because we performed so much more, a lot of that variable expense went up which obviously I think alliances we talk about the interests of our employees with the interests of our shareholders very well, and that's the beauty and that's how our models always work throughout different cycles.",
    'Sullivan Dental led by Bob, the late Bob Sullivan, and his son, Tim, shared our commitment to focusing on practice care solutions, the notion of helping practitioners operate a better practice so that they could provide better clinical care, enabled us to continue to gain market share, to hire new Team Schein Members and increase shareholder value so that today, our U.S.',
    'Holly, one of the things that we – the decision we made in having an equity piece to start out with as we wanted to be involved and be able to have a good understanding and seat at the table as we go through the permitting process, regulatory process, and a full understanding of any implications we have with delays, how we might be able to navigate the heightened enthusiasm by the activists to stop infrastructure.',
    'The difference in the revenue from external – from what we shared in our projections to what we delivered was really focused on two things, primarily licensed software from the Cerner side and from lower than expected tech resale.',
    'As we discussed on the last earnings call, while we entered the year in a clean inventory position, our spring transition receipts are as expected slightly elevated, and we worked prudently to clear this inventory during the quarter.',
    "And the second question, I lay it aside if it's related or not I guess, but there's a lot of buzz out there right now a lot of discussion and I think your stock performance today given the numbers would suggest there is a lot discussion in investor community that the numbers today are so bad the number last quarter are so bad that they are actually good for shareholders and activists will come an acquirer will come in and get involved.",
    'The customer really doesn’t touch this so they get the benefits of cloud on one hand while not having to deal with some of what the regulatory issues might be on the other hand.',
    'Like our peers, we also have some clients who are having to adopt to disruptive technologies and business models, and others who are responding to the wave of activists shareholders and private equity.',
    'The April 1, 2016 price increase in the U.K., the base rate increases in Kentucky and additional transmission margins in Pennsylvania partially offset the negative effects of the lower foreign currency exchange rate, lower sales volumes and higher depreciation and interest expense resulting from continued capital investment.',
    'Our Sage business momentum improved during the quarter, following the previously discussed product recall.',
    'In closing, the consistent execution of our strategy to deliver the highest quality, interactive entertainment experiences coupled with disciplined financial management enable Take-Two to deliver another year or better than expected revenues, profits and cash flow.',
    'And the only thing I will add is also mind the off balance sheet funds that we had given the tempering and the fund raising and investing levels, that is also bringing down our outlook, kind of our estimates for those off balance sheet funds which as you know we capture a fee on that as well too so certainly some of that core fee income adjusting downwards relates to that.',
    'Could you give us an update on expectations around clearing the inventory overhang in Europe?',
    'On the other hand, imagine the products that ACE sells, everything from environmental liability to farm and ranch to product recall, the construction and we could go on and on with a lot of product that will enhance the offerings to those verticals and also might help to expand into a few others as we go along.',
    'And of course, as you well know, once we get into the third quarter, we’ll refresh that expectation and see what it tell us at that point in time, both in terms of crisis in the market and our inventory levels and then we’ll adjust accordingly.',
    'These events help us attract top talent, great brand awareness, and gain industry credibility.',
    'While we will continue to manage the current volume environment and cost pressures, we will continue to secure our future growth through new business awards supplemented with M&A investments.',
    'And then lastly just on the – there is a lot of new supply and we already talked about how it will affect your current operations, but would you see as far as the managed business or maybe your CofO business, I guess, how much share of the new development can you take in your market, either developers wanting to affiliate with Extra Space.',
    'Our investments, in particular in specialty labor, supply chain, and increased depreciation related to strategic capital investments and ongoing pressures in the business, including approximately $40 million of lower profit share revenue in the fourth quarter will be partially offset by a combination of returns from new initiatives and ongoing cost reductions and efficiency.',
    "These savings will be partially offset, however, by the incremental investments we're making in our future growth initiatives, which for this year we expect to be in the range of $100 million to $120 million or $0.17 to $0.21 in diluted EPS.",
    'Our investments, in particular, in specialty labor, supply chain and increased depreciation related to strategic capital investments and ongoing pressures in the business, including approximately $35 million of lower profit share revenue, will be partially offset by a combination of returns from new initiatives and ongoing cost reductions and efficiencies.',
    'As an example, we have a project focused on reducing the amount of open box appliances we take into our stores by addressing root cause issues.',
    "We're investing in the customer experience and all of the enablers and then, of course, the shareholders are benefiting as well.",
    'However there was a tax benefit to Illumina following our participation in the recent Series B financing round.',
    "You'll also start to see the effect of some of the large funding program like TopMed, sort of switch from being a headwind to the upgrade to NovaSeq to being more of a tailwind.",
    'Near-term, we expect higher sequential investment in our BPS platform as well as currency headwinds attributable to a strengthening dollar against the UK pound and the euro.',
    'We believed it was appropriate at the time to increase our capital expenditures to accelerate some opportunities we think we have to better serve our customer.',
    'We will invest approximately $1 billion over the next three years in a combination of operating expense on capital.',
    'We continue to make progress across our capital investment programs to the benefit our customers and we have a strong environmental social and governance story.',
    "You guys have mentioned that's a big initiative for the Company.",
    'While we will continue investing in R&D, with spending in 2018 exceeding $160 million, going forward innovation will be prioritized across all the businesses to focus on the large initiatives that can generate the most benefit to the entire company.',
    'We will move to the new brand management organization structure, make important infrastructure investments, continue retail store development and take decisive action to mitigate foreign-currency pressures.',
    'We believe these positive organic growth trends reflect consistent capital spending by the U.S.',
    'We’re also continuing to invest in our business and we continue to look at projects that we have on the board, right, investing in technology, investing in our people.',
    'The investment in our infrastructure, our e-commerce, Henry Schein One, and the training of our field sales consultants, all of that, I believe, adds to the value we bring to the marketplace and positions us to gain market share.',
    'I wanted to follow-up on your comments regarding investments in IT platforms, and Mark, you referred to expecting some better inventory management out of the new IT system investment.',
    'Total cash investment is expected to increase a $100 million, reflecting a $125 million in cash restructuring charges offset by $25 million decrease in CapEx associated with restructuring program.',
    "And then I would put up costs related to preparing for the growth we expect in 2017 across a number of the businesses, within our senior businesses, in M&R, some of the Optum businesses where you've seen there have been very -- some significant new business awards for next year as we prepare for that.",
    'In addition to these factors, we expect continued investments around omni-channel capabilities and expenses related to the work we are doing around our global inventory assortment tools and our logistics network.',
    'Like, what are the places that you guys are going to invest in and how that kind of plays into your operating margin expectations?',
    'We expect our bempeg manufacturing investment to be significant in 2019, as we build drug supply inventory to support the multi-year clinical development plan for bempeg.',
    'But we do expect there to be certain opportunities for us to be able to invest more on the inventory side, just given the state of the market on a broader basis.',
    'Year-to-date strong top line growth was supported by working capital investment of $164 million, which we expect to convert to cash in the back half of the year, inventory built with volume increases in the quarter as well as in anticipation of a strong Q3.',
    'It’s a small quarter overall, but does that reflect some of the savings that you discussed?',
    'There isn’t service revenue associated with the In-Home Advisor specifically.',
    'And in a sense we also create – helping to create the dynamics is our merchandising efforts, our online efforts, our in-store efforts is allowing us to create that excitement about this more fully featured larger screen TVs.',
    'So this is a case where in partnership with our vendors and everything we can do we are helping to drive the market and a better outcome.',
    'So this is hard work because it’s building a new business in a sense of reinventing an existing business, but we continue to be excited by the opportunity and very focused on doing what it takes creating the right products, service offerings, also the processes to deliver, the capabilities, and then the go to market.',
    'But in the end the other place where we saw an exceptional outcome was merchandising, inventory, there was a lot of drama in Q4, [put aside] various things.',
    'We are excited about the continued television product innovation being introduced to the market.',
    'Yes, so on that one, I think when we look at the store what we’re most pleased with is our ability to offer the more premium products and the bigger solutions and the other products that go with it.',
    'Clearly these vendor partnerships partnering with our key vendors has been a big part of the story of Best Buy forever, but certainly in the last four years.',
    'It’s really a well-known product and commodity.',
    'But partnerships like this and the idea of interesting technology evolution continuing in categories like this, I think that’s what’s actually more important because I think this idea that we can showcase these technologies in unique way that no one else can, that’s what’s the real differentiator here.',
    'It’s more what that adviser enables.',
    'The questions I have and I’ll lump them together, to what extent – as you look at either your promotional plans or maybe what you’ve seen from competitors, does that seem more subdued or rational than prior years?',
    'So this is going to be, this is going to take time, but we continue to be excited about this.',
    'And I have to congratulate our Canadian team they have done a remarkable job going through that brand consolidation.',
    'business, responsible for running the domestic business and in partnership with Corie, getting us to where we want to be as a company.',
    'What matters of course during holiday includes assortments, deals, product availability, help, convenience and speed.',
    'That has been a trend that we’ve been seeing.',
    'And one of the things we’ve actually talked about, because the other kind of flavor on this question is, how do you think about the difference in profitability between the various channels and how is that evolving over time.',
    'And, we’ve talked a lot about, in our business, what we actually see as less difference between the profitability in the channels always with the caveat that things like this exactly make it very hard for us to pull the channels apart.',
    'But, this is part of the reason that the overall profitability of our online channel in particular has continued to improve over time.',
    'So, this is definitely part of when we talk about the lesser difference between the profitability of our channels.',
    'And it’s a combination of both experiences on the site, but also ways in which the customer’s choosing to come pick up their own merchandise versus necessarily wanting to shift straight to their home in every instance.',
    'This is a big part of what has helped us create a more robust online profitability profile.',
    'And sometimes, you wake up after an acquisition, oh, my God what have we done?',
    'No, we feel very, very positive about this.',
    'And so, our level of excitement is very good.',
    "So, I just want to make sure people understand that's not that that business is performing differently than we thought, it's just a bit of how it timed out amongst the quarters.",
    'We are very excited about working with the team.',
    "And, Mike, what I would say amplifying what Sharon just said, you'll find us increasingly prudent about releasing product category detailed information, because we are only focused on technology, because it's natural to ask these questions.",
    "So I don't think anything's changed from our lens around maintaining a strong balance sheet.",
    'And we can help them with any questions, they’ll tend to buy more stuff as well, which we -- but this is not what is driving it.',
    "We are excited both by our growth momentum and opportunities and we're investing in people, technology and supply chain in support of our strategy.",
    "But, I don't think you're going to see any massive speed up, you're not going to see a change in the overall positioning.",
    'I feel very good about our inventory situations.',
    'We like of course the environment in which we’ve been operating this year and we’ll provide the updates on the Q4 call, but very excited about the future for our business.',
    "We feel like it's important to get this running start early in the year and frankly I'm exceptionally proud of the teams who have even in a more rapid way than in some prior years, ramped up some of the technology build and some of the physical work in the stores even faster than we've done historically.",
    'We feel like we’re performing quite well in the switch, in particular that’s what’s driving the gaming category right now.',
    'We feel our value proposition is resonating with customers.',
    "And I don't think you spoke at great length about price investment, so does that remain a part of the margin story for you?",
    "So far, we're pleased by what we're seeing, but I don't think it's meaningful, right, as the essential idea was not simply to close stores because the customers, you're not doing anything for the customer but to reinvent the customer experience as we move forward.",
    "It's a big part of our growth strategy.",
    'And so, I think you’ve seen us talking about mobile actually as gross profit rate is attractive for a few quarter now and a lot of those different dynamics at play in the margin profile.',
    'But, this is a great example of product innovation and vendor partnerships, and the great customer experience in the stores and online driving the revenue performance.',
    'So, we tend to do really well when we’re dealing with complex systems, large cube, high touch solutions where if you need to design a smart home solution, if you need to design a music streaming solution throughout your home, as I was explaining, that tends to be a forte, either because of our in-home channel, particularly well positioned to do this or in the stores, the great place for discovery, support and service and advice.',
    'Instantly, when we grow online revenue, we don’t see it as a great way to close stores, we’re not excited about closing stores.',
    'Your first question was to expand a little bit on the change and exactly why we refined the methodology.',
    'We feel like we really are addressing a customer need, very in line with the strategy and that we are providing a whole another suite of purchase option and we will continue to see how it grows over time.',
    "Now that's very much tied to the macro environment there.",
    "And so I don't think that's a great indicator of how behaviorally people will respond, especially at the different levels of 10% to 25%, I think you are going to end up with potentially some different consumer buying behaviors.",
    "The agreements that we have, we don't bear the risk over the longer term of the agreement.",
    'The financing provided through our Best Buy credit card is an important benefit we offer customers where there are people who are going to be interested in getting a credit card who are unable to quantify for it because of low credit scores or in many cases, simply no credit history.',
    'First, strong execution of our strategy combined with better product availability; second, a continued healthy consumer confidence and positive macro conditions; third, strength in the gaming category; and fourth, a favorable competitive environment, as we benefited from the exit or decline of certain competitors.',
    'And as part of that question, maybe you can talk about what do you think is more important for the business, product cycles or the overall health of consumer spending, because maybe some of the product cycles might fade this year, but the overall spending environment might pick up.',
    "It's a huge deal because the faster I can get someone at the end of the day to that product that they're looking for with the closest match to their natural language request, the more the likelihood they're actually going to flow through on that purchase.",
    'I believe that from a working capital point of view, as I mentioned, this accounts payable to inventory ratio this year was extremely low because of the decisions and the shift of the Super Bowl.',
    'We feel like this range is thoughtful given the plans that we have in front of us, and it does incorporate all of those factors back into it.',
    "That's really – fits with the first priority I laid out, we have multiple opportunities there, we are very clear about them.",
    "And so I don't think we're at the stage yet where we can call an order run rate.",
    'Is that a pretty good run rate or are you thinking that that should accelerate or decelerate as you progress through in the launch here?',
    "So, if you add up the total number of customers or the total number of systems, I don't think we've crossed over the halfway point even off the upgrade cycle.",
    "Obviously, there were a few questions already on that, but I'm just wondering if we're at a point where growth is inflecting given the progress on a number of fronts you cited.",
    'And then also just I think one of the questions to originally and it may still be too early.',
    'Obviously, CMS is an influential player in the market.',
    "So I don't think that alone is enough to get you there.",
    'And then on NextSeq, when you pre-announced Q2 results, you more tightly linked to non-high end NGS weakness to NextSeq coming up light of expectations and then speaking with you after the announcement, you made it clear that the NextSeq shortfall was a function of a companion diagnostic partnership delay and you indicated the impact would be even more meaningful in the second half.',
    "I don't think you called out any of this in your prepared remarks today.",
    "Can you quantify the tariff pull forward but I think we'll probably get questions about maybe some of the milestones around Bristol and Loxo and then GeL which was going to tail off a bit in the back half of the year potentially?",
    'Is it a strategic partner for Visa or a potential disruptive threat?',
    "So, I don't think you should carry that forward as sort of something that would happen every year.",
    "I don't think you should view that as some kind of seasonality, it's just a reflection of what happened in the past couple of years, and just there timing was for renewal of certain deals and exactly what was going on in Europe and so on.",
    'First, could you comment on corporate card or business spend, is that can be a leading indicator for the consumer economy?',
    "I don't think our crystal ball is any better than anybody else's, and so we don't really try to predict those things.",
    "And I think in the case of tokenization, we're probably still trying to push it uphill a little bit, but I feel like we're close to the top of the hill, and we'll start seeing it roll down the hill as key merchants get enabled by these token requesters that we've recently signed.",
    "So I don't think we have a point of view on that, and it's probably a little too early in any case.",
    "Candidly, I don't see a lot of divestitures as I look out because we have really remixed the portfolio quite dramatically over the last couple of years.",
    "So I don't see any major changes in the capital allocation model as we go forward.",
    "I don't see any big delay right now in any decision-making.",
    "But I feel much stronger about the hand that we're holding right now than the hand we were holding three years or four years ago.",
    "I don't think it's going to have much margin expansion, again, because of the continuation of the investment.",
    "So to answer your question, no, I don't see, at this moment as we speak, a pause in the sales activity as a result of the proposed merger.",
    'Or maybe just a little bit of context so we understand how to forecast that group with that agreement in place?',
    "We feel confident that the $1 billion that we mentioned is an end-year synergy that we're going to be realizing from the combined entities.",
    "And if you can keep generating that kind of working capital performance, you don't have to talk ever again.",
    "So I don't see that as widespread, I don't see that as continuing in the future but it did impact this quarter, particularly in the United States.",
    "No, I don't think we're disadvantaged at all, as a matter of fact, I think what we're seeing is an absolute unique value proposition where we're able to take many of these new digital solutions and we are very experienced in being able to integrate that into the existing IT state, both application, as well as infrastructure.",
    "We're able to leverage our new scale to drive additional rate reductions for both third-party labor and non-labor expense, and we renegotiated agreements with our top strategic suppliers.",
    "But I don't think that's going to impact the overall synergy number that we talked about for next year.",
    'Not yet, I mean we’ve got some really just basic modeling on this and don’t really have anything I feel comfortable sharing, yes, I mean, certainly would be a benefit.',
    'And at what point do you think that you might have to just go out into the market and just to keep up, with hopefully is -- now a better trajectory on loan growth side?',
    "We believe that's important.",
    "We feel good about that based on balance sheet growth and even more encouraged based on what we've seen of late with the market expectations for rates.",
    "Those are very difficult to forecast, but it's also encouraging that those customers can find alternative forms of financing today.",
    "Our efficiency ratio target is intact of 62% this year, and 18 we will be in that 60% range, and so I don't think that when you deliver to 2% GDP type environment that you can take your eye off the expense ball whatsoever.",
    "Okay, so despite the fact that MPLs were flat, I mean I hear you that you feel good about it, but I guess what I’m worried about is that, I know you didn't change your charge of guidance of 30 bips to 50 bips despite coming into that 50 because of those items this quarter, is the risk to that 30 bips to 50 bips is going higher?",
    "We think that allowance will probably hover right in that area, might go down to 1, but, I don't see it going sub-1 on the allowance.",
    "Yes, I don't think that's -- I don't think, Matt, that's fairly meaningful right now.",
    'We feel pretty confident we can get there.',
    'And we’ll have – we’ll be able to toggle between loan growth and share buybacks as we seek to manage the capital at that level.',
    'Let me begin by saying in the face of significant market volatility, we are pleased with our second quarter results.',
    'We do see a fair bit of brands and Operating Systems and size loyalty and so the customers are not rushing to buy something else at this point in time so we’ll see how it evolves during the quarter but this is a pretty much hold your breath kind of a situation for many of these customers, you want to take the iPhone 7, Corie?',
    'And as we enter the back half of the year and as pricing of these technologies becomes even more affordable, we believe that we will continue to benefit from the customer moving to larger-screen televisions and 4K technology.',
    'We also recently launched a new functionality that makes it much easier for customers to find open box items both online and in-store.',
    'I think we can all agree the Apple Watch is certainly iconic and having it in all 1,000 stores by the end of September is a big deal for us.',
    'A third highlight of the quarter is the launch of the first Fire TV Edition smart TV that’s part of our product development partnership with Amazon.',
    "Second, a bigger but more important question, and I think it's one of, if not, the biggest questions with the NovaSeq launch, is whether or not it's going to lead to labs spending more on consumables than it did before?",
    'As is routine for a product launch at Illumina, we will be shipping a small number of iSeqs this quarter to be followed by a manufacturing ramp to 2018.',
    'At Arctic Cat, we introduced our new Mountain Snowmobiles, with our ground-breaking Alpha One single beam rear suspension system, further demonstrating our industry leading product innovation.',
    'We expect this inventory to come out.',
    'During the fourth quarter, we launched a fully digital pension product platform in Brazil and after regulatory approval will be owned through a joint venture with BB Seguridade.',
    'On February 1st, we made filings with the IURC seeking approval to develop three wind farms in Indiana in partnership with experienced renewable energy developers.',
    'Our filings seeking approval to develop three wind farm in Indiana in partnership with experienced renewable energy developers remain pending before the IURC, with orders expected in the third quarter of 2019.',
    'Missile-Defense Agency, in partnership with the industry team, launched two Raytheon exoatmospheric kill vehicle in back-to-back tests.',
    'With this collaboration, we will introduce the first jointly managed OpenShift offering in the public cloud, combining the power of Red Hat OpenShift, the industry’s most comprehensive enterprise Kubernetes platform, and Azure, Microsoft’s public cloud.',
    'While the ultimate transformation will take many years, upon closing of the transaction we immediately launched test-and-learn pilots aimed at both operationally and clinical improvements in four markets: Richmond, Virginia; Charlotte, North Carolina; Virginia Beach, Virginia; and Dallas, Texas.',
    'At the September meeting of the Avicenna Alliance, a global alliance of healthcare industries and researchers that was set up at the request of the European Commission, Medtronic reported that modeling and simulation helped them release the product to market two years earlier, treating 10,000 patients during this period, and saving an estimated $10 million.',
    'ANSYS tools and services are opening the doors to new opportunities in the fast-changing automotive market by providing 3M credibility in demonstrating their sensor material performance under adverse weather and lighting conditions.',
    "First, with the rollout of COVERGIRL, the new products coming as we turn into 2018, do you expect inventory destocking to negatively impact returns in that business or is there just going to be a one-in/one-out type of program, let's say, over the next couple of quarters?",
    'Lastly, we recently completed the months long global rollout of CT60 collection of watches as previously discussed we are supporting the watch category with extensive marketing to strengthen product awareness and brand credibility and heritage.',
    "Then on this morning's acquisition, do you expect to get more of that longer extended stay such as over 30 days and you intend to make that inventory exclusive to Expedia?",
    'In the second quarter, we re-launched our Lowes.com site, providing an upgraded online shopping experience with optimized functionality in display for touch-screen devices, improve product and content recommendations, refine search algorithms, larger product images and expanded product views including video content.',
    'At the end of May we launched Cloud Island, an infant brand which we developed in partnership with our guests.',
    'And this week at NAB, we announced new consumer products including our first offering for the drone marketplace, the Fly Drive, which includes enough space for 60 hours of 4K video footage and developed in partnership with top drone manufacturer, DJI.',
    'Today we are unveiling Best Buy 2020, building the new blue.',
    'And two, the assumption that potential new phone launches will occur later in the quarter than they did last year.',
    'And then at least there’s an assumption on our part based on various public indications that the launch of a new phone would happen later in the quarter, even though we don’t have a firm date at this point in time.',
    'So obviously, as we go into Q1 here, we have the switch as part of the guidance that we gave you for Q1 and the excitement around that.',
    "In appliances, we've completed our planned rollout of Pacific Kitchen & Home stores-within-a-store for the year adding 59 stores for a total of 176.",
    'We introduced Blue Assist, a new feature in our highly rated mobile app, which allows customers to simply shake their device to get live help with products and orders through chat, call, e-mail or through scheduling of Blue Shirt in-store.',
    'We also began selling AppleCare and piloting our new Apple authorized service provider capabilities in more than 60 stores.',
    'The first of these investments was the September 13 launch of our new Geek Squad services in computing and tablets.',
    "And number six, a range of services offered to our customers including free Geek Squad setup on top tech gifts and the ability for customers to give a gift of a Geek Squad agent's time.",
    'But for us at Best Buy, this shift of the iPhone launch by a week was not helpful.',
    'In the entertainment category, we have been rolling out virtual reality merchandising.',
    'My first question is as you continue to roll out the store within stores, whether it’s LG or Samsung, Sony, Oculus, collectively, what proportion of your revenues do these store in store businesses now represent?',
    'Last year in Canada, we began testing a new service offering that provides 24/7 support for all of the technology products a customer owns regardless of whether they were bought at Best Buy.',
    'For example, we launched during the quarter a new smart nursery assortment.',
    'Initially, and sometimes in these conversations, we -- when people are talking, they say, is that the Geek Squad doing this?',
    'OLED is, of course, a very significant one that we are excited about.',
    'We also launched a pilot in the Best Buy mobile app that allows customers to book 30 minute in-person appointments to consult with Blue Shirt experts.',
    'Also in Canada, we’re testing a new service called Geek Squad Home Membership that provides support for all of the technology products that customer may own regardless of whether they were bought at Best Buy.',
    'Yes, on the iPhone, we are actually seeing a pretty much just in line with what our expectations were.',
    'So I’m sure you won’t talk specifics, but as you’ve become more and more important in the way that they develop new products, that they introduce new products, that they talk to customers, I mean, how is the conversation different with the vendors than maybe broadly than 18 months ago or 36 months ago?',
    'We talked about VR and the 300,000 visits to experience VR.',
    'Portable audio, there’s also headphones.',
    'The second piece, Simeon, I want to make sure that I call out, and we said it in the release, is that we also are expecting to roll out some of these new initiatives, and we’re expecting some return on those initiatives, as well.',
    'And so we tend to be very tied to major releases and the demand around the excitement on those releases, and so it’s a little bit difficult for us to understand exactly what some of those product launches will look like.',
    'These shops feature highly trained specialists who provide access to the carriers products and services and the ability to learn about a wide set of connected or smart devices.',
    'In addition right after the end of the quarter, we launched the Best Buy app for iPad.',
    'Like AppleCare, our new Geek Squad services are much more than extended warranties.',
    'Second week, we released 8 deals.',
    'Now since then, there is been new product introductions that we can all be very familiar with.',
    'Phones, we anniversary still the comparison with a very strong phone launch, so as expected softness that we expect to reverse in the back half of the year.',
    'Maybe second question if I could, with respect to the second half guidance and you mentioned in your prepared comments, Hubert you did as well the mobile phone launches, it’s maybe kind of more qualitative statement, I mean to what extent do the mobile phone launches in some of the leading carriers or the manufacturers out there need to be successful in order to help your guidance?',
    'We talked about Apple authorized service provider historically, and you will also see some very specific offerings that we provide on some of the high end merchandise around more white glove kind of delivery and service offerings.',
    'And number five providing an integrated Geek Squad customer experience across channels and devices and driving increased attach rates.',
    'For the new phone launched last month, for example, we simplified the buying experience and provided clarity of carrier offers and ease of phone selection and saw our highest ever Android preorders.',
    'As expected, new product launches stimulated demand during the quarter.',
    'I said some words about virtual reality, but that’s not the only one and of course, we are not here to announce new product launches for – on behalf of our vendors.',
    'There’s some really cool new headphones.',
    'And I know that some of the vendors have spoken with lots of excitement about new product rollouts in the second half of the year.',
    'Also in the smart home area, we are curating new product categories across the home.',
    'And then, yes, you’re right to call out some of the later launch of mobile, which we had said earlier would push some of that into the second quarter.',
    'Is that primarily mobile and the launch late in the quarter or other drivers to consider?',
    'Hubert, you just mentioned that you’re planning on rolling out the in home advisory service to the -- nationwide later on this year.',
    'So we’re going to offer this service nationwide sometime in the back half of the year.',
    'First, on the iPhone, honestly, there’s a wide spectrum of belief in terms of how the iPhone will perform, and we know about as much as you do in terms of exactly what this phone is going to be, when it’s going to launch.',
    "And for Geek Squad, we're able to provide an array of services to our customers remotely in our stores and in their home.",
    "So first, in our computing and tablet service categories, beginning September 13, we're launching a range of services, including Geek Squad Protect & Support Plus, which combines hardware support, 24/7 software support and accidental damage in one plan priced very competitively.",
    'The additional display tables are great for the merchandising of Apple Watch, which went on sale on BestBuy.com and in more than 100 of our stores in August.',
    'We also recently launched a new program called Magnolia Care to provide ongoing support and troubleshooting for the comprehensive custom home theatre solutions we provide to our Magnolia Design Center clients.',
    'Just with some of the robustness, especially, in TVs, do you expect any alleviation in price competition as innovation remains pretty exciting going into the holiday season year-over-year?',
    'During the third quarter, we also continued to see encouraging results from our Total Tech Support program that we rolled out nationally in May.',
    'As such, and as a first step, we’ve recently rolled out new dedicated endcaps in our mobile department that showcase GreatCall’s easy-to-use mobile phone products and connected devices that are tailored for seniors and come with a range of relevant services.',
    'I mean, the number of initiatives with the shop-in-shops and some of the new news that you announced with Apple today with AppleCare and the updating of the shop-in-shop, how do you let your customers know about all these changes?',
    "I think I would say we're very excited by, again, the early momentum of Apple Watch in our stores, which, obviously, a triggered decision that we've made with Apple to have an accelerated and expanded rollout.",
    'As it relates to your second question is, does the Apple Watch momentum compared to the phone – that would be too much detail, I think, at this point.',
    "We have previewed that in previous quarter, but with the launch of Geek Squad Protect & Support Plus that's another step forward.",
    'We already have sold a variety of health-related products and technology products designed for seniors, like specially design phones and medical alert systems.',
    "And of course, they'll start selling the phones or the watch, themselves, but it’s unclear at this point what the net effect is going to be.",
    'And then, can you share with us, like if you look at your Elite Plus customers, what percentage of them are buying mobile through Best Buy, just shopping the category, I’m thinking like just as a phone as a primary purchase?',
    'And so, now, there’s some more competitive entrants, if you will, if Amazon does become a first party seller of the phone.',
    'What I would add to complement what Hubert said is, our phone business is a complicated, so people want to think about their relationship with the carriers.',
    'And so, the one thing that Best Buy’s done is try to simplify their experience, whether it’s in our stores or online, when you can actually talk to a qualified expert, you can review your plan with us, we can compare plans to other carriers, we’re very objective about that and you can compare an iOS ecosystem to an Android ecosystem.',
    'This is a key thing that consumers are going to need more help with as they keep their devices longer.',
    'And we still believe even though the consumer is truly -- and you know the statistics probably better than I do around delaying or upgrade purchase, that means they’re keeping their phone longer and they want to do other things with it.',
    'Despite this current softness, we continue to believe that over the course of the year, iconic new phone launches can drive renewed growth in this category.',
    'Year-over-year our Geek Squad agents also drove more customer interactions across our channels and helped more customers use and enjoy their technology products.',
    "So, there is always this tension of sort of looking in the near-term at what products or latest announcement, whether it's holiday or Apple, Amazon competitor announcement is going on, and then, there is a temptation to go back to product cycles that have been there historically and sort of thinking about your business.",
    'It is more -- this idea that we keep providing new and different ways for customers to get bigger TVs with better technologies.',
    'And you just rolled up Total Tech Support.',
    'What it includes is the extended warranties, installation and support services.',
    'And just one follow-up question about the mobile category, specifically, how you are thinking about Best Buy mobile standalone stores?',
    'I bet you all have seen that we were the exclusive place where you could try the Oculus in our stores.',
    'And really, a lot of that was around some of the offers that were specific to Best Buy and some of just the underlying strengths, not just the new launches but in some of the older generations of phones as well.',
    'First, from the phone standpoint, if you compare to last year, we have two iconic phones in the market compared to last year.',
    'We’re assuming there is an iPhone 8 launch and that is also a viable phone for the back half.',
    'I wanted to get your thoughts on smart home products and services.',
    'So, on the customer base, the Best Buy customer, our target customer, we’ve talked about this, is a -- we call them the high touch tech fans.',
    'The second highlight of the quarter is the rollout of our new Total Tech Support program.',
    'These drivers were partially offset by declines in our mobile phone category.',
    'I just want to stick on that Total Tech Support.',
    'This is more just a question of broadly how often are people buying what are now pretty trendy phones and replacing them.',
    'Is it all Samsung and is it all mobile and appliances and then following up on the earlier question, it sounds like you’re saying there’s very little substitution across brands, which if something breaks particularly on the appliance side, the rule of thumb is that two-thirds of demand is sort of failure or repair driven.',
    'Is it something that could be sort of a dark horse later this year?',
    'So are you more heavily weighted to brands that were dislocated because the shipping issues or is there pressure coming in from J.C.',
    'And yes, we are more weighted towards the Korean brands in appliances.',
    'One I would just start with, the last few questions were all about how you guys are really winning with more premium product and the whole experience and offering.',
    'And then just a real quick, on the appliance side, are you seeing your customers embrace connected appliances at this point?',
    'We have, of course, the display of the major brands of phones, Apple, Samsung, and increasingly Google.',
    "If one day you feel that your network is not functioning properly, and I'm assuming that that would be a widespread phenomenon or if you're asking yourself questions about how your audio or video system should evolve, we provide the service where we'll go to your home and will have a professional that will work with you, understand your situation, your needs, and come up with something that is a range of solutions.",
    "So a large piece of our TV business is not actually in UHD as well and we saw very strong television category this quarter, but we're going to be short on details from a competitive point of view as we go into holiday.",
    'Our lease-to-own program provides another option for enabling customers to make periodic payments over a fixed period eventually leading to full ownership of the product once the agreement has been fulfilled.',
    'My questions are focused on wireless.',
    'And follow up on the prior question about the cycles in the back half outlook, how are you thinking about TV, the TV category as the year progresses from the sales and gross profit dollar perspective?',
    'You closed out 2017 clearly with a lot of momentum in addition to having the NovaSeq out there without manufacturing constraints.',
    'We believe that Visa Direct provides capabilities superior to competing solutions, including pre authorization, real-time payment capability available 24/7, sending money to bank accounts as well as reloadable prepaid and credit credentials and scale to serve more than 150 countries with one systems integration, including cross border capabilities.',
    'The enterprise cloud apps team is continuing to drive this momentum by introducing 16 quick-start offerings to help clients plan, pilot and test enterprise and cloud application software accelerating their digital business solutions with software from DXC as well as our strategic partners.',
    'Okay, and in terms of the loans that you are adding now, say the indirect consumer which is in that bag, but the growth that you are getting their in terms of some of the other portfolios.',
    'And then maybe a tail off through the rest of the CCAR cycle?',
    'And as you point out, EIG, Pantheon and Baring Asia all continue to be in fund raising mode each with multiple products.',
    'And during 2018, King expects to ramp inventory with a deliberate and methodical rollout of ad product types, user cohorts and other.',
    'OEM revenue reached $251 million, reflecting sales of our cryptocurrency-specific GPUs, partially offset by the lapse in our licensing agreement with Intel.',
    'I was wondering if you could talk a little bit about the underlying expectation for the fall order book, as you start thinking about inventory buys for seasonal product in holiday in the fall of 2016.',
    'Should there be a significant market demand for super-spec rigs going forwrad, H&P has a capability of providing approximately 270 super-spec FlexRigs to the market without requiring new build rigs, solely through upgrades where needed to our current FlexRig3 and FlexRig5 fleet.',
    'Should there be significant market demand for super-spec rigs going forward, H&P has the capability of providing approximately 270 super-spec FlexRigs to the market without requiring any new builds.',
    'Hey, good morning, just one additional follow-up on Gorgon, I guess Wheatstone as well.',
    'We haven’t called for it to be sequential each quarter, but for the second half we expect to see improvement and we in the second quarter, we did move through some inventory and we still have some excess inventory in the Kate brand that we will be working through as we move the second half, but we are also seeing some traction with the assortment changes we’re making and the marketing actions we are taking as well as adding new brand spokes people to the brand.',
    'That will be true in TVs.',
    'As a reminder for everyone, this is an expert technology advisor, who has got great both product proficiency across everything we sell, and great customer relationship skills, will typically go to the customer’s house.',
    'And from a customer standpoint, this is not limited to luxury and premium.',
    'In many cases, if we want to have a discussion about your networking needs, or your home theater, or how you want to automate your home, we really need to have this conversation in your home.',
    'I wanted to ask about the consumer electronics category.',
    'I’m going to start with home theater.',
    'And how are you thinking about home theater in particular in 2017?',
    'It’s also, as you think about the unlocked and prepaid businesses being much more viable models as well for customers, which again we think is great space for us to play in because it offers choice and gives us a different way to position ourselves in the category.',
    'These products will be offered at very attractive prices to our customers throughout the holiday season.',
    'First, we have created an expansive assortment of amazing technology products, especially in 4K TVs, health and wearables, appliances, connected or smart devices, drones and many other giftable items.',
    'The portfolio has also seen an overall industry reduction in frequency of claims.',
    'Appliances is less of a giftable item maybe, but our momentum continues to be strong in the market in that category continues to be very strong.',
    'It was one of our down categories.',
    'And it seems the industry is changing to more broad-based installment billing platform.',
    'Does that change your ability to take share, and what might it do to the frequency of upgrades in your view?',
    "Looking ahead, again to the extent that there is amazing great products and so forth, number one it can help the industry and certainly will help us and we'll take advantage of it.",
    "So what we've done is we've redefined the service offering, with the Geek Squad services for computing and tablet we launched that on September 13 with Geek Squad Protect & Support Plus, and we also launched AppleCare ramping up our Apple product service provider capabilities.",
    "So we've changed the offering, moving away from sure warranties to something that is helpful to customers and we've materially lowered the price.",
    "We put deductibles in on the phone repair, which we were the only ones in the industry historically that didn't have one, you recall that.",
    'By holiday, we expect to be selling an expanded assortment of virtual reality products in the vast majority of our stores and more than 500 stores will be equipped with demo stations, so customers can try out this exciting new technology.',
    'Actually, we can show customers products that are available in the store closest to them and show which products are actually displayed in stores near them if they are interested in experiencing the product before they buy.',
    'We are also testing Geek Squad on-demand services, including same day for customers who need immediate technology help or advice.',
    'So, our computing and phones, of course a different story.',
    "So in fiscal 2016, we'll be focused on continuing to transform our traditional service offerings to better address customer needs, we will be integrating the Geek Squad customer experience into bestbuy.com to provide an enhanced service experience to our customers and to increase online attach rates.",
    "We see the tablet decline was the substantial and we need to make sure that it's in perspective.",
    'And then there is building, you can say this professional services offering instead of capabilities to help our customers.',
    'Why it’s an ingesting shift, right, because when these return products or this could be also end-of-life products, the margin on these products is actually lower by definition.',
    "Why don't you just give a little more color around the returns and damages and that opportunity there and the impact maybe that you have in the quarter, are you seeing an uptick in that?",
    'It also includes other valuable benefits like discounts on installation services and warranty programs.',
    'We expanded that pilot to additional markets in Canada, and we are now piloting a version of the program in a couple of U.S.',
    'This can make shopping for a smartphone confusing and complicated.',
    'And then also, just to pile on, are warranties beginning to have any impact on the gross margin at this point?',
    'We are, at this point, assuming there is some kind of Note launch.',
    'We’re moving from a hardware to a service period, smart home, et cetera.',
    'You have a new cycle around OLED.',
    'Specifically, as it relates to Best Buy Smart Home powered by Vivint, I want to highlight one thing, which is, given the way we are currently approaching the business with Vivint, you should assume that the bulk of the revenue recognition is going to be from the ongoing service revenue stream as opposed to the initial hardware, so which means that the top line impact is going to be very moderate.',
    'The revenue comes from what you would choose to purchase as a result of that visit, be it hardware or services.',
    'Secondly, anything on VR that might be meaningful this year?',
    'You had drones.',
    'We’re noticing, I guess, the in-stocks seem to be better on that product.',
    'This was offset by continued softness in gaming.',
    'In home theatre, we continued to grow sales and market share due to the strength of our Magnolia design centers, continued success of our vendor experiences and strong performance online.',
    'We also drove growth in several emerging product categories.',
    'Based on early results, we’ve expanded both the in-home advisor program and the Geek Squad on-demand pilots to additional markets.',
    'Our Geek Squad on-demand pilots provide services to customers who need immediate technology help or advice including same day.',
    'Home theatre outstanding results during the quarter, seems like there’s been a proliferation of 4K TV skews and maybe lower demographic channels or lower price point channels, the value channel.',
    'And then just as part of that can you also talk about computers?',
    'So on TVs, if you breakdown the industry in our business by TV size, you’ll see a very different picture and this is an important point to highlight because it’s not just about 4K’s and OLED TVs it’s very much about large screen TVs.',
    'Are there any metrics you can provide of that versus like five years ago, where I don’t know a third of TVs have a surround sound and it used to be 20% or anything?',
    'With our IHA program, customers receive a free in-home consultation with our experienced technology advisor, who can identify their needs, design personalized solutions, and become a personal resource over time.',
    'As you’ve noticed, our customers like the more advanced, tend to prefer the higher-end premium products oftentimes, and we’ve been able in multiple product categories to really developed a superior merchandising and customer experience both online and in our stores around this.',
    'That will be true in computing, for example.',
    'Hubert, I was hoping maybe you could talk a little bit more about the opportunity on in-home advisory services and products, what you saw in the tests, and in terms of average spend, and the type of customers you’re targeting, and the scalability of that?',
    'Really a nice performance in that category in the quarter, and hoping you could talk about some of the potential catalysts for that category in 2017, particularly the performance of the home theater area?',
    'Home theater continues to perform well, but it is not the biggest driver of this quarter of some of the increase we’re seeing, other things that are included in the consumer electronics category are our connected home products.',
    'But that has obviously come at lower ASPs, and what we like for us is that the balance between those two things, and the mix of business for us, that’s what Hubert commented on, this ability for us to sell the more fully featured, the up and coming technology, to really experience what a 60, 70, 90-inch TV’s looks and feels like, that mix of business for us has been very helpful and very strong.',
    'My question has to do with the product availability.',
    'I was wondering either with respect to dollars or comp, what was the impact of difficulty in procuring some of the product, and what gives you the confidence that these difficulties will be alleviated at the beginning of the second half?',
    'What we also know is that for the larger cube, higher touch categories where seeing the product, having access to an experienced sales associate, and then having the in-home experience, that set of assets is really critical for us.',
    'I was wondering if you could discuss your expectations for the gaming category in the coming year, as well as any guidance on future store closures this year?',
    'We tend to over-index on the hardware side of gaming.',
    "Additionally in mobile, we've added the ability for customers to buy installment billing plans online for Sprint.",
    'And we also launched a dedicated Windows 10 online experience that showcases the functionalities of Windows 10, offers customer training and highlights new Windows 10 devices.',
    'They include providing 24/7 support to our customers and helping them take advantage of their technology products.',
    'These periodic benefits have been driven by substantial changes we have made to our insured warranty plans from both a plan design and cost-to-fulfill perspective.',
    "There's a lot of excitement in both – in wearables, connected devices.",
    'But as you know from our remarks this morning, mobile was not our strongest category.',
    "So when we have somebody coming to your house, who understand your needs and build a solution for you, we are not going to charge for the in-home visit, but this is - this has the ability to drive business and we see it today with our Magnolia Design Centers and thus know where it's coming from.",
    'We had some plans that were multi-year plans.',
    'What is noteworthy is the superior customer experience that we have built around home theater.',
    'So surprising that you comped positive with a negative mobile dynamic, could you give us some insight on what’s driving that and is that sustainable in that category?',
    'This said, phone is not the only story.',
    'And then as you go into next year and just given that we are late in certain product cycles, do you expect that this momentum that you are seeing will continue with that category?',
    'Who wants to sit around and wait for the entire day for the appliance to show up, I think we can do a survey on this call, probably no one.',
    'One was, as we mentioned, the services pricing, where we both saw a little bit better attach and made some changes to our portfolios that were accepted well by our customers.',
    'Because there is only so much you can -- I mean there is a lot we can do remotely and today we can troubleshoot your computer remotely using online tools.',
    "So I think that's going to be a core theme, so there is going to be work on making sure that the extended warranty and products specific services are highly competitive and are effectively marketed and promoted and sold.",
    "As you know we did bring up that product on the website it's harder to find then we would like it to be.",
    'This initiative will include other enhancements such as improvements to the phone activation process, the addition of more specially trained mobile associates and new vendor displays.',
    'There are categories in there that we also don’t participate in.']
    return koko


